using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Nestly.Infrastructure.Migrations
{
    /// <summary>
    /// Task 296 (Phase 17): closes the loop between a recurring plan and the
    /// ordinary bookings it generates.
    ///
    /// <list type="number">
    /// <item><c>booking.recurring_booking_plan_id</c> - nullable FK to
    /// <c>recurring_booking_plan</c>, Restrict. Null on every one-off booking;
    /// set on each occurrence. This is what makes an occurrence "an ordinary
    /// Booking row with a FK back to the plan" rather than a parallel booking
    /// model.</item>
    /// <item><c>recurring_booking_occurrence.booking_id</c> - promoted from a
    /// loose Guid column to a real FK to <c>booking</c>, Restrict, plus a
    /// unique index. Null stays legal (a skipped occurrence created no
    /// booking) and Postgres treats every NULL as distinct, so the uniqueness
    /// constrains only the Booked rows: one booking is generated by at most
    /// one occurrence.</item>
    /// </list>
    ///
    /// STRAY-DRIFT CLEANUP: <c>ef migrations add</c> also emitted the whole of
    /// <c>20260807150601_AddDeviceTokenProviderOwner</c>'s device_token work
    /// (nullable customer_id, provider_id, its index, its check constraint and
    /// its FK) into this migration, because that task committed its migration
    /// without the regenerated <c>NestlyDbContextModelSnapshot.cs</c> - the
    /// exact trap <c>database/scripts/add-migration.sh</c> documents. Those
    /// operations are deleted from this file by hand: re-running them would
    /// fail on any database that already applied that migration. The
    /// regenerated snapshot committed alongside this file DOES include them,
    /// which is what repairs the drift for the next migration author.
    /// </summary>
    public partial class AddRecurringPlanBookingLink : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "recurring_booking_plan_id",
                table: "booking",
                type: "uuid",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "ix_booking_recurring_booking_plan_id",
                table: "booking",
                column: "recurring_booking_plan_id");

            migrationBuilder.AddForeignKey(
                name: "fk_booking_recurring_booking_plans_recurring_booking_plan_id",
                table: "booking",
                column: "recurring_booking_plan_id",
                principalTable: "recurring_booking_plan",
                principalColumn: "id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.CreateIndex(
                name: "ix_recurring_booking_occurrence_booking_id",
                table: "recurring_booking_occurrence",
                column: "booking_id",
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "fk_recurring_booking_occurrence_booking_booking_id",
                table: "recurring_booking_occurrence",
                column: "booking_id",
                principalTable: "booking",
                principalColumn: "id",
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_recurring_booking_occurrence_booking_booking_id",
                table: "recurring_booking_occurrence");

            migrationBuilder.DropIndex(
                name: "ix_recurring_booking_occurrence_booking_id",
                table: "recurring_booking_occurrence");

            migrationBuilder.DropForeignKey(
                name: "fk_booking_recurring_booking_plans_recurring_booking_plan_id",
                table: "booking");

            migrationBuilder.DropIndex(
                name: "ix_booking_recurring_booking_plan_id",
                table: "booking");

            migrationBuilder.DropColumn(
                name: "recurring_booking_plan_id",
                table: "booking");
        }
    }
}
