// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nestly.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nestly.Infrastructure.Migrations
{
    [DbContext(typeof(NestlyDbContext))]
    partial class NestlyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nestly.Application.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mobile");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Pincode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pincode");

                    b.Property<string>("State")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("state");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_customer");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_customer_email")
                        .HasFilter("email IS NOT NULL");

                    b.HasIndex("Mobile")
                        .IsUnique()
                        .HasDatabaseName("ix_customer_mobile");

                    b.ToTable("customer", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("actor_type");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_name");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("OccurredOnUtc")
                        .IsDescending()
                        .HasDatabaseName("ix_audit_log_occurred_on_utc");

                    b.HasIndex("ActorType", "ActorId")
                        .HasDatabaseName("ix_audit_log_actor_type_actor_id");

                    b.HasIndex("EntityName", "EntityId")
                        .HasDatabaseName("ix_audit_log_entity_name_entity_id");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AddOnTotalSnapshot")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("add_on_total_snapshot");

                    b.Property<string>("AddressCitySnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("address_city_snapshot");

                    b.Property<string>("AddressContactMobileSnapshot")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("address_contact_mobile_snapshot");

                    b.Property<string>("AddressContactNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_contact_name_snapshot");

                    b.Property<string>("AddressLabelSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("address_label_snapshot");

                    b.Property<string>("AddressLandmarkSnapshot")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_landmark_snapshot");

                    b.Property<decimal>("AddressLatitudeSnapshot")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("address_latitude_snapshot");

                    b.Property<string>("AddressLine1Snapshot")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address_line1snapshot");

                    b.Property<string>("AddressLine2Snapshot")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address_line2snapshot");

                    b.Property<decimal>("AddressLongitudeSnapshot")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("address_longitude_snapshot");

                    b.Property<string>("AddressPincodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("address_pincode_snapshot");

                    b.Property<string>("AddressStateSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("address_state_snapshot");

                    b.Property<decimal>("BasePriceSnapshot")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("base_price_snapshot");

                    b.Property<decimal>("BaseTotalSnapshot")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("base_total_snapshot");

                    b.Property<string>("CouponCodeSnapshot")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("coupon_code_snapshot");

                    b.Property<decimal?>("CouponDiscountAmountSnapshot")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("coupon_discount_amount_snapshot");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerMobileSnapshot")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("customer_mobile_snapshot");

                    b.Property<string>("CustomerNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_name_snapshot");

                    b.Property<decimal>("PlatformFeeSnapshot")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("platform_fee_snapshot");

                    b.Property<int>("QuantitySnapshot")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_snapshot");

                    b.Property<DateOnly>("SlotDate")
                        .HasColumnType("date")
                        .HasColumnName("slot_date");

                    b.Property<TimeSpan>("SlotEndTimeSnapshot")
                        .HasColumnType("interval")
                        .HasColumnName("slot_end_time_snapshot");

                    b.Property<TimeSpan>("SlotStartTimeSnapshot")
                        .HasColumnType("interval")
                        .HasColumnName("slot_start_time_snapshot");

                    b.Property<Guid>("SlotWindowId")
                        .HasColumnType("uuid")
                        .HasColumnName("slot_window_id");

                    b.Property<string>("SlotWindowNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slot_window_name_snapshot");

                    b.Property<Guid?>("SourceAddressId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_address_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<decimal>("SubtotalSnapshot")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("subtotal_snapshot");

                    b.Property<decimal>("TaxAmountSnapshot")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("tax_amount_snapshot");

                    b.Property<decimal>("TaxPercentageSnapshot")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("tax_percentage_snapshot");

                    b.Property<decimal>("TotalPayableSnapshot")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_payable_snapshot");

                    b.Property<decimal>("VisitChargeSnapshot")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("visit_charge_snapshot");

                    b.HasKey("Id")
                        .HasName("pk_booking");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_booking_created_at_utc");

                    b.HasIndex("CustomerId", "Status")
                        .HasDatabaseName("ix_booking_customer_id_status");

                    b.ToTable("booking", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.BookingAddOnItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_item_id");

                    b.Property<decimal>("LineTotalSnapshot")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("line_total_snapshot");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_snapshot");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("ServiceAddOnId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_add_on_id");

                    b.Property<decimal>("UnitPriceSnapshot")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_price_snapshot");

                    b.HasKey("Id")
                        .HasName("pk_booking_addon_item");

                    b.HasIndex("BookingItemId")
                        .HasDatabaseName("ix_booking_addon_item_booking_item_id");

                    b.ToTable("booking_addon_item", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.BookingItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<decimal>("LineTotalSnapshot")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("line_total_snapshot");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_snapshot");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<string>("SlugSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug_snapshot");

                    b.Property<decimal>("UnitPriceSnapshot")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_price_snapshot");

                    b.HasKey("Id")
                        .HasName("pk_booking_item");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_booking_item_booking_id");

                    b.ToTable("booking_item", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.BookingStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at_utc");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("from_status");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_booking_status_history");

                    b.HasIndex("BookingId", "ChangedAtUtc")
                        .HasDatabaseName("ix_booking_status_history_booking_id_changed_at_utc");

                    b.ToTable("booking_status_history", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BannerUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("banner_url");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icon_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean")
                        .HasColumnName("is_featured");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("SeoMetaDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("seo_meta_description");

                    b.Property<string>("SeoTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("seo_title");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_category");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_category_slug");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.CategoryCityMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("Id")
                        .HasName("pk_category_city_mapping");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_category_city_mapping_city_id");

                    b.HasIndex("CategoryId", "CityId")
                        .IsUnique()
                        .HasDatabaseName("ix_category_city_mapping_category_id_city_id");

                    b.ToTable("category_city_mapping", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("StateId")
                        .HasColumnType("uuid")
                        .HasColumnName("state_id");

                    b.HasKey("Id")
                        .HasName("pk_city");

                    b.HasIndex("StateId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_city_state_id_name");

                    b.ToTable("city", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.CityPricingPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<decimal>("PlatformFee")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("platform_fee");

                    b.Property<decimal>("TaxPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("tax_percentage");

                    b.Property<decimal>("VisitCharge")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("visit_charge");

                    b.HasKey("Id")
                        .HasName("pk_city_pricing_policy");

                    b.HasIndex("CityId")
                        .IsUnique()
                        .HasDatabaseName("ix_city_pricing_policy_city_id");

                    b.ToTable("city_pricing_policy", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApplicableCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("applicable_category_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CustomerSegment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("customer_segment");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("discount_type");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("discount_value");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("MaxDiscountAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("max_discount_amount");

                    b.Property<decimal>("MinOrderAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("min_order_amount");

                    b.Property<int>("RedemptionCount")
                        .HasColumnType("integer")
                        .HasColumnName("redemption_count");

                    b.Property<int?>("UsageLimitPerCustomer")
                        .HasColumnType("integer")
                        .HasColumnName("usage_limit_per_customer");

                    b.Property<int?>("UsageLimitTotal")
                        .HasColumnType("integer")
                        .HasColumnName("usage_limit_total");

                    b.Property<DateTime>("ValidFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from_utc");

                    b.Property<DateTime>("ValidToUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to_utc");

                    b.HasKey("Id")
                        .HasName("pk_coupon");

                    b.HasIndex("ApplicableCategoryId")
                        .HasDatabaseName("ix_coupon_applicable_category_id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_coupon_code");

                    b.HasIndex("ValidFromUtc", "ValidToUtc")
                        .HasDatabaseName("ix_coupon_valid_from_utc_valid_to_utc");

                    b.ToTable("coupon", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.CouponRedemption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<Guid>("CouponId")
                        .HasColumnType("uuid")
                        .HasColumnName("coupon_id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("discount_amount");

                    b.Property<DateTime>("RedeemedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redeemed_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_coupon_redemption");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("ix_coupon_redemption_booking_id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_coupon_redemption_customer_id");

                    b.HasIndex("CouponId", "CustomerId")
                        .HasDatabaseName("ix_coupon_redemption_coupon_id_customer_id");

                    b.ToTable("coupon_redemption", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.CustomerAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("ContactMobile")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contact_mobile");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contact_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<string>("Landmark")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("landmark");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("latitude");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("line1");

                    b.Property<string>("Line2")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("line2");

                    b.Property<Guid?>("LocalityId")
                        .HasColumnType("uuid")
                        .HasColumnName("locality_id");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("pincode");

                    b.Property<Guid?>("PincodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("pincode_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("state");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_customer_address");

                    b.HasIndex("LocalityId")
                        .HasDatabaseName("ix_customer_address_locality_id");

                    b.HasIndex("PincodeId")
                        .HasDatabaseName("ix_customer_address_pincode_id");

                    b.HasIndex(new[] { "CustomerId" }, "ix_customer_address_all")
                        .HasDatabaseName("ix_customer_address_customer_id");

                    b.HasIndex(new[] { "CustomerId" }, "ix_customer_address_one_default_per_customer")
                        .IsUnique()
                        .HasDatabaseName("ix_customer_address_customer_id1")
                        .HasFilter("is_default = true");

                    b.ToTable("customer_address", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.CustomerAuthIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("identifier");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("provider");

                    b.HasKey("Id")
                        .HasName("pk_customer_auth_identity");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_customer_auth_identity_customer_id");

                    b.HasIndex("Provider", "Identifier")
                        .IsUnique()
                        .HasDatabaseName("ix_customer_auth_identity_provider_identifier");

                    b.ToTable("customer_auth_identity", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.CustomerCommunicationPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<bool>("PromotionalEmailEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("promotional_email_enabled");

                    b.Property<bool>("PromotionalSmsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("promotional_sms_enabled");

                    b.Property<bool>("PromotionalWhatsAppEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("promotional_whatsapp_enabled");

                    b.Property<bool>("PushEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("push_enabled");

                    b.Property<bool>("TransactionalEmailEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("transactional_email_enabled");

                    b.Property<bool>("TransactionalSmsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("transactional_sms_enabled");

                    b.Property<bool>("TransactionalWhatsAppEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("transactional_whatsapp_enabled");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_customer_communication_preference");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("ix_customer_communication_preference_customer_id");

                    b.ToTable("customer_communication_preference", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.CustomerOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("code_hash");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("purpose");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target");

                    b.HasKey("Id")
                        .HasName("pk_customer_otp");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_customer_otp_customer_id");

                    b.HasIndex("Target")
                        .HasDatabaseName("ix_customer_otp_target");

                    b.ToTable("customer_otp", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.CustomerSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("device_info");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.HasKey("Id")
                        .HasName("pk_customer_session");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_customer_session_customer_id");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_customer_session_refresh_token_hash");

                    b.ToTable("customer_session", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.Locality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("PincodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("pincode_id");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("zone_id");

                    b.HasKey("Id")
                        .HasName("pk_locality");

                    b.HasIndex("PincodeId")
                        .HasDatabaseName("ix_locality_pincode_id");

                    b.HasIndex("ZoneId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_locality_zone_id_name");

                    b.ToTable("locality", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.LoginAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("identifier");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("boolean")
                        .HasColumnName("succeeded");

                    b.HasKey("Id")
                        .HasName("pk_login_attempt");

                    b.HasIndex("Identifier", "OccurredAtUtc")
                        .HasDatabaseName("ix_login_attempt_identifier_occurred_at_utc");

                    b.ToTable("login_attempt", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.PaymentAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("GatewayOrderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("gateway_order_id");

                    b.Property<string>("GatewayPaymentRef")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("gateway_payment_ref");

                    b.Property<Guid>("PaymentTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_transaction_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_payment_attempt");

                    b.HasIndex("GatewayOrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_payment_attempt_gateway_order_id");

                    b.HasIndex("PaymentTransactionId", "AttemptNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_payment_attempt_payment_transaction_id_attempt_number");

                    b.ToTable("payment_attempt", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_payment_transaction");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("ix_payment_transaction_booking_id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_payment_transaction_customer_id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_payment_transaction_idempotency_key");

                    b.ToTable("payment_transaction", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.Pincode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("Id")
                        .HasName("pk_pincode");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_pincode_city_id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_pincode_code");

                    b.ToTable("pincode", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.RefundTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("GatewayRefundRef")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("gateway_refund_ref");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("method");

                    b.Property<Guid>("PaymentTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_transaction_id");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_refund_transaction");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_refund_transaction_booking_id");

                    b.HasIndex("PaymentTransactionId")
                        .HasDatabaseName("ix_refund_transaction_payment_transaction_id");

                    b.ToTable("refund_transaction", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationPolicy")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("cancellation_policy");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Exclusions")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasDefaultValue("")
                        .HasColumnName("exclusions");

                    b.Property<string>("Inclusions")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasDefaultValue("")
                        .HasColumnName("inclusions");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("ReschedulePolicy")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reschedule_policy");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_service");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_service_category_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_service_slug");

                    b.ToTable("service", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.ServiceAddOn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_service_addon");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_service_addon_service_id");

                    b.ToTable("service_addon", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.ServiceCityPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.HasKey("Id")
                        .HasName("pk_service_city_price");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_service_city_price_city_id");

                    b.HasIndex("ServiceId", "CityId")
                        .IsUnique()
                        .HasDatabaseName("ix_service_city_price_service_id_city_id");

                    b.ToTable("service_city_price", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.ServiceFaq", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("answer");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("question");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.HasKey("Id")
                        .HasName("pk_service_faq");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_service_faq_service_id");

                    b.ToTable("service_faq", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.ServiceMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_service_media");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_service_media_service_id");

                    b.ToTable("service_media", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.ServicePincodeMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("PincodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("pincode_id");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.HasKey("Id")
                        .HasName("pk_service_pincode_mapping");

                    b.HasIndex("PincodeId")
                        .HasDatabaseName("ix_service_pincode_mapping_pincode_id");

                    b.HasIndex("ServiceId", "PincodeId")
                        .IsUnique()
                        .HasDatabaseName("ix_service_pincode_mapping_service_id_pincode_id");

                    b.ToTable("service_pincode_mapping", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.SlotBlackout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_slot_blackout");

                    b.HasIndex("CityId", "StartDate", "EndDate")
                        .HasDatabaseName("ix_slot_blackout_city_id_start_date_end_date");

                    b.ToTable("slot_blackout", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.SlotBookingPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<int>("CutoffMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("cutoff_minutes");

                    b.Property<int>("MaxAdvanceDays")
                        .HasColumnType("integer")
                        .HasColumnName("max_advance_days");

                    b.HasKey("Id")
                        .HasName("pk_slot_booking_policy");

                    b.HasIndex("CityId")
                        .IsUnique()
                        .HasDatabaseName("ix_slot_booking_policy_city_id");

                    b.ToTable("slot_booking_policy", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.SlotWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("MaxBookingsPerSlot")
                        .HasColumnType("integer")
                        .HasColumnName("max_bookings_per_slot");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("pk_slot_window");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_slot_window_city_id");

                    b.ToTable("slot_window", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.SlotWindowRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<Guid>("SlotWindowId")
                        .HasColumnType("uuid")
                        .HasColumnName("slot_window_id");

                    b.HasKey("Id")
                        .HasName("pk_slot_window_rule");

                    b.HasIndex("SlotWindowId", "DayOfWeek")
                        .IsUnique()
                        .HasDatabaseName("ix_slot_window_rule_slot_window_id_day_of_week");

                    b.ToTable("slot_window_rule", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.State", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_state");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_state_code");

                    b.ToTable("state", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.SupportTicketComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("SupportTicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("support_ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_support_ticket_comment");

                    b.ToTable("support_ticket_comment", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.WalletLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<decimal>("BalanceAfter")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("balance_after");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("entry_type");

                    b.Property<Guid?>("SourceReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_reference_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source_type");

                    b.HasKey("Id")
                        .HasName("pk_wallet_ledger");

                    b.HasIndex("CustomerId", "CreatedAtUtc")
                        .HasDatabaseName("ix_wallet_ledger_customer_id_created_at_utc");

                    b.ToTable("wallet_ledger", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_zone");

                    b.HasIndex("CityId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_zone_city_id_name");

                    b.ToTable("zone", (string)null);
                });

            modelBuilder.Entity("Nestly.Domain.Booking", b =>
                {
                    b.HasOne("Nestly.Application.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_booking_customer_customer_id");
                });

            modelBuilder.Entity("Nestly.Domain.BookingAddOnItem", b =>
                {
                    b.HasOne("Nestly.Domain.BookingItem", null)
                        .WithMany("AddOns")
                        .HasForeignKey("BookingItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_addon_item_booking_items_booking_item_id");
                });

            modelBuilder.Entity("Nestly.Domain.BookingItem", b =>
                {
                    b.HasOne("Nestly.Domain.Booking", null)
                        .WithMany("Items")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_item_booking_booking_id");
                });

            modelBuilder.Entity("Nestly.Domain.BookingStatusHistory", b =>
                {
                    b.HasOne("Nestly.Domain.Booking", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_status_history_booking_booking_id");
                });

            modelBuilder.Entity("Nestly.Domain.CategoryCityMapping", b =>
                {
                    b.HasOne("Nestly.Domain.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_category_city_mapping_category_category_id");

                    b.HasOne("Nestly.Domain.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_category_city_mapping_cities_city_id");
                });

            modelBuilder.Entity("Nestly.Domain.City", b =>
                {
                    b.HasOne("Nestly.Domain.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_city_states_state_id");

                    b.Navigation("State");
                });

            modelBuilder.Entity("Nestly.Domain.CityPricingPolicy", b =>
                {
                    b.HasOne("Nestly.Domain.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_city_pricing_policy_city_city_id");
                });

            modelBuilder.Entity("Nestly.Domain.Coupon", b =>
                {
                    b.HasOne("Nestly.Domain.Category", null)
                        .WithMany()
                        .HasForeignKey("ApplicableCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_coupon_category_applicable_category_id");
                });

            modelBuilder.Entity("Nestly.Domain.CouponRedemption", b =>
                {
                    b.HasOne("Nestly.Domain.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_coupon_redemption_booking_booking_id");

                    b.HasOne("Nestly.Domain.Coupon", null)
                        .WithMany()
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_coupon_redemption_coupon_coupon_id");

                    b.HasOne("Nestly.Application.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_coupon_redemption_customer_customer_id");
                });

            modelBuilder.Entity("Nestly.Domain.CustomerAddress", b =>
                {
                    b.HasOne("Nestly.Domain.Locality", null)
                        .WithMany()
                        .HasForeignKey("LocalityId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_customer_address_localities_locality_id");

                    b.HasOne("Nestly.Domain.Pincode", null)
                        .WithMany()
                        .HasForeignKey("PincodeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_customer_address_pincodes_pincode_id");
                });

            modelBuilder.Entity("Nestly.Domain.Locality", b =>
                {
                    b.HasOne("Nestly.Domain.Pincode", "Pincode")
                        .WithMany()
                        .HasForeignKey("PincodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_locality_pincodes_pincode_id");

                    b.HasOne("Nestly.Domain.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_locality_zones_zone_id");

                    b.Navigation("Pincode");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Nestly.Domain.PaymentAttempt", b =>
                {
                    b.HasOne("Nestly.Domain.PaymentTransaction", null)
                        .WithMany("Attempts")
                        .HasForeignKey("PaymentTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payment_attempt_payment_transactions_payment_transaction_id");
                });

            modelBuilder.Entity("Nestly.Domain.PaymentTransaction", b =>
                {
                    b.HasOne("Nestly.Domain.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payment_transaction_booking_booking_id");

                    b.HasOne("Nestly.Application.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payment_transaction_customer_customer_id");
                });

            modelBuilder.Entity("Nestly.Domain.Pincode", b =>
                {
                    b.HasOne("Nestly.Domain.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pincode_city_city_id");

                    b.Navigation("City");
                });

            modelBuilder.Entity("Nestly.Domain.RefundTransaction", b =>
                {
                    b.HasOne("Nestly.Domain.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refund_transaction_booking_booking_id");

                    b.HasOne("Nestly.Domain.PaymentTransaction", null)
                        .WithMany()
                        .HasForeignKey("PaymentTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refund_transaction_payment_transaction_payment_transaction_");
                });

            modelBuilder.Entity("Nestly.Domain.ServiceCityPrice", b =>
                {
                    b.HasOne("Nestly.Domain.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_city_price_city_city_id");

                    b.HasOne("Nestly.Domain.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_city_price_service_service_id");
                });

            modelBuilder.Entity("Nestly.Domain.ServicePincodeMapping", b =>
                {
                    b.HasOne("Nestly.Domain.Pincode", null)
                        .WithMany()
                        .HasForeignKey("PincodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_pincode_mapping_pincode_pincode_id");

                    b.HasOne("Nestly.Domain.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_pincode_mapping_service_service_id");
                });

            modelBuilder.Entity("Nestly.Domain.SlotBlackout", b =>
                {
                    b.HasOne("Nestly.Domain.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_slot_blackout_city_city_id");
                });

            modelBuilder.Entity("Nestly.Domain.SlotBookingPolicy", b =>
                {
                    b.HasOne("Nestly.Domain.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_slot_booking_policy_city_city_id");
                });

            modelBuilder.Entity("Nestly.Domain.SlotWindow", b =>
                {
                    b.HasOne("Nestly.Domain.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_slot_window_city_city_id");

                    b.Navigation("City");
                });

            modelBuilder.Entity("Nestly.Domain.SlotWindowRule", b =>
                {
                    b.HasOne("Nestly.Domain.SlotWindow", "SlotWindow")
                        .WithMany()
                        .HasForeignKey("SlotWindowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_slot_window_rule_slot_window_slot_window_id");

                    b.Navigation("SlotWindow");
                });

            modelBuilder.Entity("Nestly.Domain.WalletLedgerEntry", b =>
                {
                    b.HasOne("Nestly.Application.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_wallet_ledger_customer_customer_id");
                });

            modelBuilder.Entity("Nestly.Domain.Zone", b =>
                {
                    b.HasOne("Nestly.Domain.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_zone_city_city_id");

                    b.Navigation("City");
                });

            modelBuilder.Entity("Nestly.Domain.Booking", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("Nestly.Domain.BookingItem", b =>
                {
                    b.Navigation("AddOns");
                });

            modelBuilder.Entity("Nestly.Domain.PaymentTransaction", b =>
                {
                    b.Navigation("Attempts");
                });
#pragma warning restore 612, 618
        }
    }
}
