using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Nestly.Domain;

namespace Nestly.Infrastructure.Persistence.Configurations;

public class RecurringBookingOccurrenceConfiguration : IEntityTypeConfiguration<RecurringBookingOccurrence>
{
    public void Configure(EntityTypeBuilder<RecurringBookingOccurrence> builder)
    {
        builder.ToTable("recurring_booking_occurrence");
        builder.HasKey(x => x.Id);

        builder.Property(x => x.RecurringBookingPlanId).IsRequired();
        builder.HasOne<RecurringBookingPlan>()
            .WithMany()
            .HasForeignKey(x => x.RecurringBookingPlanId)
            .OnDelete(DeleteBehavior.Cascade);

        builder.Property(x => x.ScheduledDate).IsRequired();
        builder.Property(x => x.Outcome).IsRequired().HasConversion<string>().HasMaxLength(30);
        // Task 296: promoted from a bare Guid? to a real foreign key. Null for
        // a skipped occurrence (no booking was created), non-null and unique
        // for a Booked one - a booking is generated by at most one occurrence
        // of one plan, and Postgres treats every NULL as distinct from every
        // other, so the unique index constrains only the Booked rows.
        // Restrict, not Cascade: deleting a booking out from under the audit
        // row that records it was ever generated would erase the evidence the
        // occurrence log exists to keep.
        builder.Property(x => x.BookingId);
        builder.HasOne<Booking>()
            .WithMany()
            .HasForeignKey(x => x.BookingId)
            .OnDelete(DeleteBehavior.Restrict);
        builder.HasIndex(x => x.BookingId).IsUnique();

        builder.Property(x => x.SkipReason).HasMaxLength(500);
        builder.Property(x => x.ProcessedAtUtc).IsRequired();

        // The scheduler's idempotency guard (class doc comment) - one row per
        // (plan, scheduled date), regardless of outcome.
        builder.HasIndex(x => new { x.RecurringBookingPlanId, x.ScheduledDate }).IsUnique();
    }
}
