using Nestly.BuildingBlocks.Primitives;

namespace Nestly.Domain;

/// <summary>The standard admin report kinds this export queue can generate (SRS 12.18.1, tasks 128a-128c).</summary>
public enum ExportReportType
{
    /// <summary>Booking listing plus successful-payment revenue total over a date range (task 128a).</summary>
    BookingRevenue,

    /// <summary>Refund transactions over a date range (task 128b).</summary>
    RefundUsage,

    /// <summary>Coupon redemption counts/totals, grouped by coupon, over a date range (task 128b).</summary>
    CouponUsage,

    /// <summary>Customer counts segmented by status and by city (task 128c).</summary>
    CustomerSegmentation,

    /// <summary>Support ticket volume/resolution-time stats over a date range (task 128c).</summary>
    SupportTicket
}

/// <summary>Lifecycle of an asynchronously generated report export (SRS 12.18.2 "Large report export may be asynchronous", task 128d).</summary>
public enum ExportJobStatus
{
    Pending,
    Processing,
    Completed,
    Failed
}

/// <summary>
/// A permission-gated, admin-initiated background export request (SRS
/// 12.18.2, task 128d): captures the same filters the instant/synchronous
/// report endpoints accept (<see cref="Nestly.Application.Reports.IReportingQueryService"/>),
/// generated by a Hangfire job (<see cref="Nestly.Application.Reports.IExportJobService.ProcessAsync"/>)
/// rather than the request thread, and polled/downloaded once complete
/// instead of holding an HTTP request open for however long a large export
/// takes. The generated CSV is stored inline (<see cref="ResultContent"/>)
/// rather than on a filesystem/blob store - report exports are bounded,
/// modest-sized text payloads, and the project has no existing blob-storage
/// abstraction to reuse (introducing one would be scope well beyond this
/// task); a bytea column keeps the job's result colocated with its own
/// status row and requires no new infrastructure dependency.
/// </summary>
public class ExportJob : Entity<Guid>
{
    public ExportReportType ReportType { get; private set; }

    /// <summary>Start of the reporting window (inclusive). Ignored by <see cref="ExportReportType.CustomerSegmentation"/>, which reports on current customer state rather than a date-bounded event stream.</summary>
    public DateTime FromUtc { get; private set; }

    public DateTime ToUtc { get; private set; }

    /// <summary>Optional city filter (SRS 12.18.2 "Filter-based export") - applies to <see cref="ExportReportType.BookingRevenue"/> only.</summary>
    public string? City { get; private set; }

    /// <summary>Optional category filter - applies to <see cref="ExportReportType.BookingRevenue"/> only.</summary>
    public Guid? CategoryId { get; private set; }

    public ExportJobStatus Status { get; private set; }

    public Guid RequestedByAdminUserId { get; private set; }

    public DateTime RequestedAtUtc { get; private set; }

    public DateTime? CompletedAtUtc { get; private set; }

    public string? ResultFileName { get; private set; }

    public byte[]? ResultContent { get; private set; }

    public string? ErrorMessage { get; private set; }

    protected ExportJob() { }

    public ExportJob(
        Guid id,
        ExportReportType reportType,
        DateTime fromUtc,
        DateTime toUtc,
        string? city,
        Guid? categoryId,
        Guid requestedByAdminUserId) : base(id)
    {
        ReportType = reportType;
        FromUtc = fromUtc;
        ToUtc = toUtc;
        City = city;
        CategoryId = categoryId;
        RequestedByAdminUserId = requestedByAdminUserId;
        Status = ExportJobStatus.Pending;
        RequestedAtUtc = DateTime.UtcNow;
    }

    public void MarkProcessing()
    {
        Status = ExportJobStatus.Processing;
    }

    public void MarkCompleted(string fileName, byte[] content)
    {
        Status = ExportJobStatus.Completed;
        ResultFileName = fileName;
        ResultContent = content;
        CompletedAtUtc = DateTime.UtcNow;
    }

    /// <summary><paramref name="errorMessage"/> is surfaced to the requesting admin, never a raw exception - it must never carry connection strings or other sensitive detail.</summary>
    public void MarkFailed(string errorMessage)
    {
        Status = ExportJobStatus.Failed;
        ErrorMessage = errorMessage;
        CompletedAtUtc = DateTime.UtcNow;
    }
}
